name: .NET

on:
  push:
    branches: [ "*" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore ./SignalsDotnet
    - name: Build
      run: dotnet build  ./SignalsDotnet --no-restore
    - name: Test
      run: dotnet test ./SignalsDotnet/SignalsDotnet.Tests --no-build --verbosity normal